

insert into sma_trn_UserPreference ([prefTopSearch]
           ,[prefUserID]
           ,[preDtCreated]
           ,[preDtModified]
           ,[preCreatedUserID]
           ,[preModifiedUserID]
           ,[preAutoEmailNotification]
           ,[preEmailNotificationByStaff]
           ,[preWorkflowEmailNotification]
           ,[preAutoCorrect]
           ,[preTheme]
           ,[preDocumentsEmailNotification]
           ,[preAttachDocumentToEmail]
           ,[preGenerateLocally]
           ,[preMyClosedCaseNotification]
           ,[preNoteFontName]
           ,[preNoteFontSize]
           ,[preDocumentShowEmail]
           ,[preTaskCompleteNotify]
           ,[preSMSEmailNotification]
           ,[KeepMergeCodes]
           ,[preTopSearchListID]
           ,[preSOLEmailNotification]
           ,[preDocDirection]
           ,[preDocCategories]
           ,[preOpenNewTabForSearch]
           ,[preDocumentRenamePattern]
           ,[preEmailPreferences]
           ,[preSendEmailsFromOutlook]
           ,[preTopSearchMode]
           ,[preDocumentPhotograph]
           ,[preTasksPreferences]
           ,[preTopSearchSaveFilter]
           ,[preNotesAdded]
           ,[preAppointmentsAdded]
           ,[preLargeGridDefaultPagingSize]
           ,[preDownloadZipFolderOption]
           ,[preDownloadDocForEdit]
           ,[preSMSSendEmailNotification]
           ,[preUserCaseRole]
           ,[preAppendFileNameToDescriptionOnMassDocUpload]
           ,[preAppendFileNameToDescriptionOnAttachDocument]
           ,[preTimeZone] )

select distinct [prefTopSearch]
           ,usrnUserID
           ,[preDtCreated]
           ,[preDtModified]
           ,[preCreatedUserID]
           ,[preModifiedUserID]
           ,[preAutoEmailNotification]
           ,[preEmailNotificationByStaff]
           ,[preWorkflowEmailNotification]
           ,[preAutoCorrect]
           ,[preTheme]
           ,[preDocumentsEmailNotification]
           ,[preAttachDocumentToEmail]
           ,[preGenerateLocally]
           ,[preMyClosedCaseNotification]
           ,[preNoteFontName]
           ,[preNoteFontSize]
           ,[preDocumentShowEmail]
           ,[preTaskCompleteNotify]
           ,[preSMSEmailNotification]
           ,[KeepMergeCodes]
           ,[preTopSearchListID]
           ,[preSOLEmailNotification]
           ,[preDocDirection]
           ,[preDocCategories]
           ,[preOpenNewTabForSearch]
           ,[preDocumentRenamePattern]
           ,[preEmailPreferences]
           ,[preSendEmailsFromOutlook]
           ,[preTopSearchMode]
           ,[preDocumentPhotograph]
           ,[preTasksPreferences]
           ,[preTopSearchSaveFilter]
           ,[preNotesAdded]
           ,[preAppointmentsAdded]
           ,[preLargeGridDefaultPagingSize]
           ,[preDownloadZipFolderOption]
           ,[preDownloadDocForEdit]
           ,[preSMSSendEmailNotification]
           ,[preUserCaseRole]
           ,[preAppendFileNameToDescriptionOnMassDocUpload]
           ,[preAppendFileNameToDescriptionOnAttachDocument]
           ,[preTimeZone]
	  from sma_mst_users 
	  cross join sma_trn_UserPreference
	  where not exists(select * from sma_trn_UserPreference where usrnUserID=prefUserID)